# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/hw7-tutorial',
                'doc_host': 'https://tpringle02.github.io',
                'git_url': 'https://github.com/tpringle02/hw7-tutorial',
                'lib_path': 'hw7_tutorial'},
  'syms': {'hw7_tutorial.core': {'hw7_tutorial.core.foo': ('core.html#foo', 'hw7_tutorial/core.py')}}}